[main]
default_profile_id = 0
admin_email = me@supme.ru
gonder_email = gonder@supme.ru

[database]
#string = dbusername:dbuserpassword@unix(/var/run/mysqld/mysqld.sock)/databasename
string = dbusername:dbuserpassword@tcp(127.0.0.1:3306)/databasename
connections = 25

[mailer]
send = false
max_campaigns = 10
dns_cache = true

[utm]
default_url = http://localhost:8080
templates_dir = ./templates
files_dir = ./files
port = 8080

[api]
port = 7777
panel_path = /panel
panel_locale = ru-ru

# default profile, which can be overridden by explicitly entering the configuration
[[profile]]
id = 0
name = Default
stream = 10
resend_count = 2
resend_delay = 1200

[[profile]]
id = 1
name = Example
hostname = mail001.example.com
interface = 1.2.3.4
#stream need only for interface
stream = 10
resend_count = 2
resend_delay = 1200

[[profile]]
id = 2
name = Group example
hostname = group
interface = 0,1,3
resend_count = 2
resend_delay = 1200

[[profile]]
id = 3
name = Example2
hostname = mail002.example.com
interface = socks://2.3.4.5:1080
#stream need only for interface
stream = 10
resend_count = 2
resend_delay = 1200

[[profile]]
id = 4
name = Example3
hostname = socks://user:pass@mail003.example.com:1080
interface = 3.4.5.6
stream = 10
resend_count = 2
resend_delay = 1200
